[package]
name = "pika-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
pika-core = { path = "../pika-core" }
duckdb = { version = "1.3", features = ["bundled"] }
arrow = "50.0"
tokio = { version = "1.35", features = ["full"] }
async-trait = "0.1"
wgpu = "0.17"
bytemuck = { version = "1.14", features = ["derive"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
parking_lot = "0.12"
futures = "0.3"
egui = "0.24"
egui-wgpu = "0.24"
thiserror = "1.0"
chrono = "0.4"
uuid = { version = "1.6", features = ["v4", "serde"] }
moka = { version = "0.12", features = ["future"] }
sysinfo = "0.30"

[dev-dependencies]
tempfile = "3.8"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "data_extraction_bench"
harness = false

[[bench]]
name = "query_bench"
harness = false
