[package]
name = "pika-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
pika-core = { path = "../pika-core" }
pika-engine = { path = "../pika-engine" }
egui = "0.24"
egui-wgpu = "0.24"
egui_plot = "0.24"
eframe = "0.24"
arrow = "50.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
parking_lot = "0.12"
rfd = "0.12"
image = "0.24"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "canvas_bench"
harness = false
